os: osx
language: swift
osx_image: xcode12.4
script: 'xcodebuild clean test -project todo-list-app.xcodeproj -scheme "todo-list-app" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.4,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO'
notifications:
    email:
        recipients:
            -ayokunle.fatokimi@decagon.dev
            -fatokimiemman@gmail.com
        on_success: always
        on_failure: always
